name: Tests
on:
  pull_request:
    paths-ignore:
      - "README.md"
  push:
    paths-ignore:
      - "README.md"
  schedule:
    - cron: "0 4 * * *"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: "1.15"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.4.0

      - name: Get dependencies
        run: |
          go mod download

      - name: Build
        run: |
          go build -v .

  test:
    name: Matrix Test
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - "1.0.8"
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: "1.15"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.4.0

      - name: Get dependencies
        run: |
          go mod download

      - name: TF acceptance tests
        timeout-minutes: 10
        env:
          TF_ACC: "1"
          TF_ACC_TERRAFORM_VERSION: ${{ matrix.terraform }}
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
        run: |
          go test -v -cover ./internal/jira/
